export const CATEGORY_ACTIONS = {
  ADD_CATEGORY: "ADD_CATEGORY",
  RENAME_CATEGORY: "RENAME_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
};

export const NOTE_ACTIONS = {
  ADD_NOTE: "ADD_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
  ADD_TO_TRASH: "ADD_TO_TRASH",
  DELETE_NOTE: "DELETE_NOTE",
  LAST_UPDATED: "LAST_UPDATED",
  ADD_CATEGORY_TO_NOTE: "ADD_CATEGORY_TO_NOTE",
  DOWNLOAD_NOTE: "DOWNLOAD_NOTE",
  EMPTY_TRASH:"EMPTY_TRASH",
};

export const ACTIVE_NOTE_ID_ACTION = "ACTIVE_NOTE_ID_ACTION";
